language: node_js
node_js:
  - node
  - 6
  - 5
addons:
  code_climate:
    repo_token: 1d359c8ec322c5371b0e4785740b1bbf21e5b7d61e836078077c87cd730ec017
before_script:
  - npm run scripts && npm run styles
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
